import test from 'node:test';import assert from 'node:assert/strict';import {calculate,VARIABLES,DIMENSIONS,actionsFor,PERIODICITY,applyOverride,exportCase,importCase,toCSV,normalizeCase,finalizeCase,validateClinicalValue} from '../src/clinical.js';import {prestratify,NETWORK_FREE} from '../src/extractor.js';
const allNo=()=>{const values=Object.fromEntries(VARIABLES.map(v=>[v.id,'no'])); values.pharmGoals='yes'; return {values,age:40,bmi:22,adultClinic:true,pathologies:['asthma']}};
const ids=['activeSmoking','nonAdherence','worseningMeds','ismpHighRisk','cognitiveSensory','polypharmacy','nonRespComorbidity','mentalDisorder','socioeconomic','hospitalUrgency','severityOxygen','naiveHospitalTherapy','medicationChanges6m'];
function formFor(points){let f=allNo();let sum=0;for(const id of ids){const v=VARIABLES.find(x=>x.id===id);if(sum+v.points<=points){f.values[id]='yes';sum+=v.points}} if(sum!==points) throw Error('bad combo '+points+' got '+sum); return f}
test('umbrales y mínimos',()=>{assert.equal(calculate(allNo()).calculatedPriority,'P3');assert.equal(calculate(formFor(20)).calculatedPriority,'P3');assert.equal(calculate(formFor(21)).calculatedPriority,'P2');assert.equal(calculate(formFor(31)).calculatedPriority,'P2');assert.equal(calculate(formFor(32)).calculatedPriority,'P1')});
test('máximos',()=>{let f={values:Object.fromEntries(VARIABLES.map(v=>[v.id,'yes'])),age:70,bmi:30,adultClinic:true,pathologies:['cf','copd']};f.values.pharmGoals='no';let r=calculate(f);assert.equal(r.total,59);assert.deepEqual(r.subtotals,{demographic:5,clinical:14,treatment:21,social:16,utilization:3});assert.deepEqual(Object.fromEntries(Object.entries(DIMENSIONS).map(([k,d])=>[k,d.max])),{demographic:5,clinical:14,treatment:21,social:16,utilization:3})});
test('excepciones',()=>{let f=allNo();f.values.pregnancyPuerperium='yes';assert.equal(calculate(f).calculatedPriority,'P1');f=allNo();f.age=17;f.values.age='adult';assert.equal(calculate(f).calculatedPriority,'P1');f=allNo();f.age=12;f.adultClinic=false;f.values.age='pediatric';assert.ok(calculate(f).pediatric)});
test('edad e imc',()=>{let f=allNo();f.age=70;f.values.age='adult';assert.equal(calculate(f).details.find(d=>d.variable.id==='age').points,2);f=allNo();f.bmi=30;f.values.bmi='set';assert.equal(calculate(f).details.find(d=>d.variable.id==='bmi').points,3);f=allNo();f.bmi=18.3;f.values.bmi='set';assert.equal(calculate(f).details.find(d=>d.variable.id==='bmi').points,1);f.pathologies=['cf'];assert.equal(calculate(f).details.find(d=>d.variable.id==='bmi').points,3)});
test('tratamiento específicos',()=>{let f=allNo();f.values.pharmGoals='yes';assert.equal(calculate(f).details.find(d=>d.variable.id==='pharmGoals').points,0);f.values.pharmGoals='no';assert.equal(calculate(f).details.find(d=>d.variable.id==='pharmGoals').points,2);f.values.naiveHospitalTherapy='yes';f.pathologies=['copd'];assert.equal(calculate(f).details.find(d=>d.variable.id==='naiveHospitalTherapy').points,1);f=allNo();f.values.complexHospitalMeds='no';assert.equal(calculate(f).details.find(d=>d.variable.id==='complexHospitalMeds').points,0)});
test('utilización y pendientes',()=>{let f=allNo();f.values.hospitalUrgency='yes';assert.equal(calculate(f).details.find(d=>d.variable.id==='hospitalUrgency').points,3);f.values.hospitalUrgency='no';assert.equal(calculate(f).details.find(d=>d.variable.id==='hospitalUrgency').points,0);delete f.values.activeSmoking;assert.equal(calculate(f).pending,true)});
test('actuaciones periodicidad override io',()=>{assert.ok(actionsFor('P1').sft.items.length>actionsFor('P2').sft.items.length);assert.match(PERIODICITY.P1,/3–6/);let r=calculate(allNo());assert.equal(applyOverride(r,{priority:'P2',justification:'criterio profesional documentado'}).finalPriority,'P2');let f=importCase(exportCase(allNo()));assert.equal(f.age,40);assert.match(toCSV(r.details),/Variable;Respuesta;Puntos/)});
test('extractor seguridad y lenguaje',()=>{let r=prestratify('Niega tabaquismo. Posible oxigenoterapia por antecedente familiar. IMC 18,3. 2 urgencias respiratorias.');assert.ok(r.some(x=>x.status==='ausencia_explicita'));assert.ok(r.some(x=>x.status==='dudoso'));assert.equal(NETWORK_FREE,true);const src=String(prestratify);assert.doesNotMatch(src,/fetch|XMLHttpRequest|OpenAI|Anthropic|Azure/i)});
test('normaliza identificación profesional y compatibilidad antigua',()=>{const old={center:' Hospital X ',pharmacist:' Farmacéutica Y ',values:{},pathologies:[]};const f=importCase(JSON.stringify({schema:'siaf-cmo-respiratorio-v1',form:old}));assert.equal(f.hospital,'Hospital X');assert.equal(f.pharmacist,'Farmacéutica Y');assert.equal(f.status,'draft');assert.equal(f.completedAt,null);assert.match(exportCase(f),/"hospital": "Hospital X"/);assert.match(toCSV(calculate(allNo()).details,f),/Hospital X/)});
test('validación de valores clínicos y finalización compatible',()=>{const v=VARIABLES.find(x=>x.id==='activeSmoking');assert.equal(validateClinicalValue(v,'yes'),true);assert.equal(validateClinicalValue(v,'set'),false);const done=finalizeCase({...allNo(),hospital:' H ',pharmacist:' F '},'provisional');assert.equal(done.hospital,'H');assert.equal(done.pharmacist,'F');assert.equal(done.status,'provisional');assert.ok(done.completedAt)});
test('caso EPOC extractor confirma 16 puntos sin duplicar y deja pendientes',()=>{const text='Paciente con EPOC en tratamiento con ocho principios activos. Presenta mala adherencia al tratamiento y continúa como fumador activo. Precisa oxigenoterapia domiciliaria. Durante el último año ha acudido dos veces a urgencias por descompensación respiratoria.';const proposals=prestratify(text).filter(x=>x.status==='detectado');const ids=['nonAdherence','polypharmacy','activeSmoking','severityOxygen','hospitalUrgency'];for(const id of ids)assert.ok(proposals.some(p=>p.variableId===id),id);const f={values:{},pathologies:['copd'],adultClinic:true,hospital:'H',pharmacist:'F'};for(const id of ids)f.values[id]='yes';let r=calculate(f);assert.equal(r.total,16);assert.equal(r.calculatedPriority,'P3');assert.equal(r.pending,true);for(const id of ids)f.values[id]='yes';assert.equal(calculate(f).total,16);const done=finalizeCase(f,'provisional');assert.equal(done.status,'provisional')});
test('intervenciones acumulativas',()=>{for(const group of Object.keys(actionsFor('P3')))assert.ok(actionsFor('P2')[group].items.length>=actionsFor('P3')[group].items.length);for(const group of Object.keys(actionsFor('P2')))assert.ok(actionsFor('P1')[group].items.length>=actionsFor('P2')[group].items.length)});
