import test from 'node:test';import assert from 'node:assert/strict';import {calculate,VARIABLES,DIMENSIONS,actionsFor,PERIODICITY,applyOverride,exportCase,importCase,toCSV} from '../src/clinical.js';import {prestratify,NETWORK_FREE} from '../src/extractor.js';
const allNo=()=>{const values=Object.fromEntries(VARIABLES.map(v=>[v.id,'no'])); values.pharmGoals='yes'; return {values,age:40,bmi:22,adultClinic:true,pathologies:['asthma']}};
const ids=['activeSmoking','nonAdherence','worseningMeds','ismpHighRisk','cognitiveSensory','polypharmacy','nonRespComorbidity','mentalDisorder','socioeconomic','hospitalUrgency','severityOxygen','naiveHospitalTherapy','medicationChanges6m'];
function formFor(points){let f=allNo();let sum=0;for(const id of ids){const v=VARIABLES.find(x=>x.id===id);if(sum+v.points<=points){f.values[id]='yes';sum+=v.points}} if(sum!==points) throw Error('bad combo '+points+' got '+sum); return f}
test('umbrales y mínimos',()=>{assert.equal(calculate(allNo()).calculatedPriority,'P3');assert.equal(calculate(formFor(20)).calculatedPriority,'P3');assert.equal(calculate(formFor(21)).calculatedPriority,'P2');assert.equal(calculate(formFor(31)).calculatedPriority,'P2');assert.equal(calculate(formFor(32)).calculatedPriority,'P1')});
test('máximos',()=>{let f={values:Object.fromEntries(VARIABLES.map(v=>[v.id,'yes'])),age:70,bmi:30,adultClinic:true,pathologies:['cf','copd']};f.values.pharmGoals='no';let r=calculate(f);assert.equal(r.total,59);assert.deepEqual(r.subtotals,{demographic:5,clinical:14,treatment:21,social:16,utilization:3});assert.deepEqual(Object.fromEntries(Object.entries(DIMENSIONS).map(([k,d])=>[k,d.max])),{demographic:5,clinical:14,treatment:21,social:16,utilization:3})});
test('excepciones',()=>{let f=allNo();f.values.pregnancyPuerperium='yes';assert.equal(calculate(f).calculatedPriority,'P1');f=allNo();f.age=17;f.values.age='adult';assert.equal(calculate(f).calculatedPriority,'P1');f=allNo();f.age=12;f.adultClinic=false;f.values.age='pediatric';assert.ok(calculate(f).pediatric)});
test('edad e imc',()=>{let f=allNo();f.age=70;f.values.age='adult';assert.equal(calculate(f).details.find(d=>d.variable.id==='age').points,2);f=allNo();f.bmi=30;f.values.bmi='set';assert.equal(calculate(f).details.find(d=>d.variable.id==='bmi').points,3);f=allNo();f.bmi=18.3;f.values.bmi='set';assert.equal(calculate(f).details.find(d=>d.variable.id==='bmi').points,1);f.pathologies=['cf'];assert.equal(calculate(f).details.find(d=>d.variable.id==='bmi').points,3)});
test('tratamiento específicos',()=>{let f=allNo();f.values.pharmGoals='yes';assert.equal(calculate(f).details.find(d=>d.variable.id==='pharmGoals').points,0);f.values.pharmGoals='no';assert.equal(calculate(f).details.find(d=>d.variable.id==='pharmGoals').points,2);f.values.naiveHospitalTherapy='yes';f.pathologies=['copd'];assert.equal(calculate(f).details.find(d=>d.variable.id==='naiveHospitalTherapy').points,1);f=allNo();f.values.complexHospitalMeds='no';assert.equal(calculate(f).details.find(d=>d.variable.id==='complexHospitalMeds').points,0)});
test('utilización y pendientes',()=>{let f=allNo();f.values.hospitalUrgency='yes';assert.equal(calculate(f).details.find(d=>d.variable.id==='hospitalUrgency').points,3);f.values.hospitalUrgency='no';assert.equal(calculate(f).details.find(d=>d.variable.id==='hospitalUrgency').points,0);delete f.values.activeSmoking;assert.equal(calculate(f).pending,true)});
test('actuaciones periodicidad override io',()=>{assert.ok(actionsFor('P1').sft.items.length>actionsFor('P2').sft.items.length);assert.match(PERIODICITY.P1,/3–6/);let r=calculate(allNo());assert.equal(applyOverride(r,{priority:'P2',justification:'criterio profesional documentado'}).finalPriority,'P2');let f=importCase(exportCase(allNo()));assert.equal(f.age,40);assert.match(toCSV(r.details),/Variable;Respuesta;Puntos/)});
test('extractor seguridad y lenguaje',()=>{let r=prestratify('Niega tabaquismo. Posible oxigenoterapia por antecedente familiar. IMC 18,3. 2 urgencias respiratorias.');assert.ok(r.some(x=>x.status==='ausencia_explicita'));assert.ok(r.some(x=>x.status==='dudoso'));assert.equal(NETWORK_FREE,true);const src=String(prestratify);assert.doesNotMatch(src,/fetch|XMLHttpRequest|OpenAI|Anthropic|Azure/i)});
