import {VARIABLES,DIMENSIONS,PATHOLOGIES,calculate,actionsFor,PERIODICITY,exportCase,importCase,toCSV,applyOverride,normalizeCase,finalizeCase,validateClinicalValue} from './clinical.js';
import {prestratify} from './extractor.js';
import {allCases,saveCase,deleteCase,clearCases} from './storage.js';
let form=normalizeCase({values:{},pathologies:[],adultClinic:true});
const $=s=>document.querySelector(s); const el=(t,a={},h='')=>{const e=document.createElement(t);Object.entries(a).forEach(([k,v])=>e.setAttribute(k,v));e.innerHTML=h;return e};
const variableById=id=>VARIABLES.find(v=>v.id===id);
function render(){renderForm(); hydrateForm(); update(); renderSaved(); renderFinalPanel();}
function hydrateForm(){ $('#pseudo').value=form.pseudoId||''; $('#hospital').value=form.hospital||form.center||''; $('#pharmacist').value=form.pharmacist||''; $('#overridePriority').value=form.override?.priority||''; $('#overrideMotive').value=form.override?.motive||''; $('#overrideJustification').value=form.override?.justification||''; document.querySelectorAll('#pathologies input').forEach(i=>i.checked=(form.pathologies||[]).includes(i.value)); document.querySelectorAll('select[data-var]').forEach(s=>{s.value=form.values?.[s.dataset.var]||'pending'}); if($('#age')) $('#age').value=form.age||''; if($('#bmi')) $('#bmi').value=form.bmi||''; if($('#adultClinic')) $('#adultClinic').checked=form.adultClinic!==false; }
function setClinicalVariable(variableId,value,source='manual'){
 const v=variableById(variableId); if(!v) return {ok:false,message:'La propuesta no corresponde a ninguna variable clínica reconocida.'};
 const normalized=value==='set_age'||value==='set_bmi'?'set':value;
 if(!validateClinicalValue(v,normalized)) return {ok:false,message:`El valor propuesto no es admisible para ${v.label}.`};
 form.values={...(form.values||{}),[variableId]:normalized}; form.status='draft'; form.completedAt=null;
 const control=document.querySelector(`[data-var="${CSS.escape(variableId)}"]`); if(!control) return {ok:false,message:`No se ha encontrado el control del formulario para ${v.label}.`};
 control.value=normalized; control.dispatchEvent(new Event('change',{bubbles:true})); update(source); return {ok:true};
}
function renderForm(){const p=$('#pathologies'); p.innerHTML=PATHOLOGIES.map(([id,l])=>`<label><input type="checkbox" value="${id}"> ${l}</label>`).join(''); p.onchange=()=>{form.pathologies=[...p.querySelectorAll(':checked')].map(i=>i.value); form.mainPathology=form.pathologies[0]||''; markDraft(); update();}; $('#variables').innerHTML=''; for(const [dim,d] of Object.entries(DIMENSIONS)){const sec=el('section',{class:'panel'},`<h2>${d.label} <span id="sub-${dim}" class="chip"></span></h2>`); VARIABLES.filter(v=>v.dim===dim).forEach(v=>{const card=el('div',{class:'var-card'},`<h3>${v.label}</h3><p>${v.help||''}</p><div id="ctrl-${v.id}"></div>`); const c=card.querySelector('div'); if(v.type==='age') c.innerHTML='<input id="age" type="number" min="0" placeholder="Edad"><label><input id="adultClinic" type="checkbox" checked> Atendido en consulta de adultos</label><select data-var="age"><option value="pending">Pendiente</option><option value="adult">Aplicar edad registrada</option><option value="pediatric">Edad pediátrica: derivar</option></select>'; else if(v.type==='bmi') c.innerHTML='<input id="bmi" type="number" step="0.1" placeholder="IMC"><select data-var="bmi"><option value="pending">Pendiente</option><option value="set">Aplicar IMC registrado</option></select>'; else if(v.type==='goals') c.innerHTML='<select data-var="pharmGoals"><option value="pending">Pendiente</option><option value="yes">Sí, alcanzados</option><option value="no">No alcanzados / inicio reciente</option></select>'; else c.innerHTML=`<select data-var="${v.id}"><option value="pending">Pendiente</option><option value="yes">Sí</option><option value="no">No</option></select>`; sec.append(card);}); $('#variables').append(sec);} document.querySelectorAll('select[data-var]').forEach(s=>s.onchange=()=>{form.values={...(form.values||{}),[s.dataset.var]:s.value}; markDraft(); update();}); ['age','bmi','adultClinic'].forEach(id=>$('#'+id)&&( $('#'+id).oninput=()=>{form[id]=$('#'+id).type==='checkbox'?$('#'+id).checked:$('#'+id).value; markDraft(); update();}));}
function markDraft(){if(form.status==='completed'||form.status==='provisional'){form.status='draft';form.outdated=true;}}
function update(){form.pseudoId=$('#pseudo').value.trim();form.hospital=$('#hospital').value.trim();delete form.center;form.pharmacist=$('#pharmacist').value.trim();form.override={priority:$('#overridePriority').value,justification:$('#overrideJustification').value.trim(),motive:$('#overrideMotive').value.trim()}; let r=calculate(form); try{r=applyOverride(r,form.override)}catch(e){} $('#score').textContent=`${r.total}/59`; $('#priority').textContent=r.finalPriority; $('#provisional').textContent=form.outdated?'Pendiente de actualizar':(r.pending?'Provisional: datos pendientes':'Completo'); $('#auto').textContent=r.pediatric||r.automaticCauses.join('; ')||'Sin prioridad automática'; for(const [k,v] of Object.entries(r.subtotals)) $('#sub-'+k)?.replaceChildren(document.createTextNode(`${v}/${DIMENSIONS[k].max}`)); $('#detail').innerHTML=r.details.map(d=>`<tr><td>${d.variable.label}</td><td>${d.response}</td><td>${d.points}</td></tr>`).join(''); $('#actions').innerHTML=renderActions(r.finalPriority)+`<p><strong>Periodicidad:</strong> ${PERIODICITY[r.finalPriority]}</p>`; window.currentResult=r; renderFinalPanel();}
function renderActions(priority){return Object.values(actionsFor(priority)).map(g=>`<h3>${g.label}</h3><ul>${g.items.map(i=>`<li>${i}</li>`).join('')}</ul>`).join('')}
['pseudo','hospital','pharmacist','overridePriority','overrideJustification','overrideMotive'].forEach(id=>setTimeout(()=>$('#'+id).oninput=()=>{markDraft();update()}));
$('#save').onclick=()=>{form=saveCase(form); renderSaved(); announce('Caso guardado localmente')}; $('#exportJson').onclick=()=>download('caso-respiratorio.json',exportCase(form)); $('#exportCsv').onclick=()=>download('detalle-respiratorio.csv',toCSV(window.currentResult.details,form)); $('#summary').onclick=()=>download('resumen-clinico.txt',report()); $('#print').onclick=()=>print(); $('#import').onchange=e=>e.target.files[0].text().then(t=>{try{form=importCase(t); render()}catch(err){announce('JSON inválido o incompatible')}}); $('#clear').onclick=()=>confirm('¿Borrar todos los casos locales?')&&(clearCases(),renderSaved());
$('#extract').onclick=()=>{const res=prestratify($('#clinicalText').value); $('#clinicalText').value=''; $('#extractResults').innerHTML=res.filter(x=>x.status!=='no_mencionado').map((x,i)=>`<div class="proposal" data-proposal-index="${i}"><b>${variableById(x.variableId)?.label||x.variableId}</b>: ${x.status} (${x.certainty})<br><small>${x.fragment}</small><br><em>${x.rule}</em><br><button type="button" data-accept="${x.variableId}" data-val="${x.proposal}">Confirmar</button><button type="button" data-reject>Rechazar</button><span class="proposal-state" aria-live="polite"></span></div>`).join('')||'Sin propuestas'; document.querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>{const box=b.closest('.proposal'),msg=box.querySelector('.proposal-state'),result=setClinicalVariable(b.dataset.accept,b.dataset.val,'extractor'); if(result.ok){box.classList.add('confirmed'); msg.textContent=' Confirmada'; box.querySelectorAll('button').forEach(x=>x.disabled=true); announce('Propuesta confirmada y trasladada al formulario.')}else{box.classList.add('error'); msg.textContent=' '+result.message; announce(result.message)}}); document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>{const box=b.closest('.proposal'); box.classList.add('rejected'); box.querySelector('.proposal-state').textContent=' Rechazada'; box.querySelectorAll('button').forEach(x=>x.disabled=true); announce('Propuesta rechazada')});};
$('#finish').onclick=()=>finish(false); $('#finishProvisional').onclick=()=>finish(true); $('#backToForm').onclick=()=>{$('#pendingDialog').hidden=true; $('#variables select')?.focus();};
function finish(allowProvisional){clearValidation(); update(); const missing=[]; if(!form.hospital) missing.push(['hospital','Indique el hospital o centro sanitario.']); if(!form.pharmacist) missing.push(['pharmacist','Indique el farmacéutico responsable.']); if(missing.length){showFieldError(missing[0][0],missing.map(m=>m[1]).join(' ')); return;} const r=calculate(form); const pending=r.details.filter(d=>d.pending); if(pending.length&&!allowProvisional){$('#pendingList').innerHTML=pending.map(d=>`<li>${d.variable.label}</li>`).join(''); $('#pendingCount').textContent=pending.length; $('#pendingDialog').hidden=false; $('#pendingDialog').focus(); return;} form=finalizeCase(form,allowProvisional?'provisional':'completed'); update(); renderFinalPanel(true); saveCase(form);}
function renderFinalPanel(focus=false){const panel=$('#finalResult'); if(!panel)return; if(!form.completedAt){panel.hidden=true;return;} const r=calculate(form); let rr=r; try{rr=applyOverride(r,form.override)}catch(e){} const pending=rr.details.filter(d=>d.pending); panel.hidden=false; panel.className=`panel result ${rr.finalPriority.toLowerCase()}`; panel.innerHTML=`<h2>Resultado de estratificación <span class="priority-badge">${rr.finalPriority}</span></h2>${form.status==='provisional'?'<p class="warning"><strong>Resultado provisional: existen variables clínicas pendientes de valoración.</strong></p>':''}${form.outdated?'<p class="warning"><strong>Resultado pendiente de actualizar.</strong></p>':''}<dl><dt>Paciente</dt><dd>${form.pseudoId||'seudónimo'}</dd><dt>Hospital o centro sanitario</dt><dd>${form.hospital||''}</dd><dt>Farmacéutico responsable</dt><dd>${form.pharmacist||''}</dd><dt>Finalización</dt><dd>${new Date(form.completedAt).toLocaleString('es-ES')}</dd><dt>Patología principal</dt><dd>${PATHOLOGIES.find(p=>p[0]===form.mainPathology)?.[1]||'No indicada'}</dd><dt>Patologías adicionales</dt><dd>${(form.pathologies||[]).filter(p=>p!==form.mainPathology).map(id=>PATHOLOGIES.find(p=>p[0]===id)?.[1]).filter(Boolean).join(', ')||'No indicadas'}</dd><dt>Puntuación total</dt><dd>${rr.total}/59</dd><dt>Prioridad calculada</dt><dd>${rr.calculatedPriority}</dd><dt>Prioridad final</dt><dd>${rr.finalPriority}</dd><dt>Prioridad automática</dt><dd>${rr.pediatric||rr.automaticCauses.join('; ')||'No'}</dd><dt>Estado</dt><dd>${form.status==='completed'?'Definitivo':'Provisional'}</dd><dt>Variables</dt><dd>${VARIABLES.length-pending.length} completadas, ${pending.length} pendientes</dd><dt>Periodicidad</dt><dd>${PERIODICITY[rr.finalPriority]}</dd></dl><h3>Subtotales</h3><ul>${Object.entries(rr.subtotals).map(([k,v])=>`<li>${DIMENSIONS[k].label}: ${v}/${DIMENSIONS[k].max}</li>`).join('')}</ul><h3>Intervenciones farmacéuticas aplicables</h3>${renderActions(rr.finalPriority)}<button type="button" id="panelSummary">Descargar resumen</button><button type="button" id="panelPrint">Imprimir</button>`; $('#panelSummary').onclick=()=>download('resumen-clinico.txt',report()); $('#panelPrint').onclick=()=>print(); if(focus){panel.setAttribute('tabindex','-1'); panel.scrollIntoView({behavior:'smooth'}); panel.focus(); announce('Resultado de estratificación generado.')}}
function clearValidation(){['hospital','pharmacist'].forEach(id=>{$('#'+id).removeAttribute('aria-invalid')}); $('#validation').textContent=''}
function showFieldError(id,msg){$('#'+id).setAttribute('aria-invalid','true'); $('#validation').textContent=msg; $('#'+id).focus();}
function announce(msg){$('#live').textContent=msg;}
function renderSaved(){ $('#saved').innerHTML=allCases().map(c=>`<li>${c.pseudoId||c.id} <button type="button" data-load="${c.id}">Cargar</button> <button type="button" data-del="${c.id}">Borrar</button></li>`).join(''); document.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{form=normalizeCase(allCases().find(c=>c.id===b.dataset.load)); render()}); document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>confirm('¿Borrar este caso?')&&(deleteCase(b.dataset.del),renderSaved()));}
function download(n,t){const a=el('a',{href:URL.createObjectURL(new Blob([t],{type:'text/plain'})),download:n});a.click();}
function report(){const r=window.currentResult;return `SIAF-CMO Respiratorio\nPaciente: ${form.pseudoId||'seudónimo'}\nHospital o centro sanitario: ${form.hospital||''}\nFarmacéutico responsable: ${form.pharmacist||''}\nFinalización: ${form.completedAt||'No finalizada'}\nPrioridad calculada: ${r.calculatedPriority}\nPrioridad final: ${r.finalPriority}\nPuntuación: ${r.total}/59\nEstado: ${form.status==='provisional'?'Resultado provisional: existen variables clínicas pendientes de valoración.':form.status||'draft'}\nPeriodicidad: ${PERIODICITY[r.finalPriority]}\n\nIntervenciones\n${Object.values(actionsFor(r.finalPriority)).map(g=>`${g.label}\n- ${g.items.join('\n- ')}`).join('\n')}`}
render();
